server:
  port: 9000

spring:
  application:
    name: zuul-notafiscal

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

zuul:
  ignoredServices: '*'
  routes:
    emissao:
      path: /nfe/emitir/**
      serviceId: notafiscal
      stripPrefix: false
      sensitiveHeaders: Cookie, Set-Cookie
    consulta:
      path: /nfe/consultar/**
      serviceId: notafiscal
      stripPrefix: false
      sensitiveHeaders: Cookie, Set-Cookie
